@gerenciador_de_arquivos_HostAddress = http://localhost:5128

### Criar Usuário
POST {{gerenciador_de_arquivos_HostAddress}}/api/User
Content-Type: application/json

{
  "userName": "usuarioTeste",
  "password": "senhaForte123"
}